[CONFIG]
# fahrenheit or celcius
temperature_unit = fahrenheit

# mph or kph
windspeed_unit = mph

# inch or centimeter
precipitation_unit = inch

timezone = auto

[LOCATION]
location_lat = 40.7130466
location_lon = 74.0072301
